/*
 * This source file was generated by the Gradle 'init' task
 */
package com.stockapp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ServiceLoader;

class AppTest {
    @Test
    //Test cconnecctivity to yahoo finance and whether the stock data is fetched successfully or not
    void testServiceExecution() {
        ServiceLoader<App.MyService> loader = ServiceLoader.load(App.MyService.class);
        boolean serviceExecuted = false;
        for (App.MyService service : loader) {
            service.execute();
            serviceExecuted = true;
        }
        assertTrue(serviceExecuted, "Service should be executed");
    }
}